baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Trident Moon'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/profile.php?id=61556987980351"
  instagram = "https://www.instagram.com/tridentmoonyoga"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/fm-sky.jpg"
  recent_posts_number = 2
  cover_dimming_class = "bg-black-00"
  site_header_text_background_color = "rgba(50, 50, 50, 0.7);"
  page_header_text_background_color = "rgba(50, 50, 50, 0.7)"
  custom_css = ["custom.css"]

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "ashtanga"
  name = "Aśṭāṅga"
  url = "/ashtanga/"
  weight = 2

[[menu.main]]
  identifier = "teacher"
  name = "Teacher"
  url = "/teacher/"
  weight = 3 


[[menu.main]]
  identifier = "classes"
  name = "Classes"
  url = "/classes/"
  weight = 4 

[[menu.main]]
  identifier = "post"
  name = "Blog"
  url = "/post/"
  weight = 5 

[[menu.main]]
  identifier = "more"
  name = "Resources"
  url = "#"
  weight = 6 

[[menu.main]]
  identifier = "links"
  name = "Cheatsheets and Links"
  parent = "more"
  url = "/sheets/"
  weight = 1

[[menu.main]]
  identifier = "primary"
  name = "Postures"
  parent = "more"
  url = "/primary/"
  weight = 2





